implement Apple Home Page Clone
che30/Apple-Clone-Microverse pull request #1
Opened 2020-09-28 02:19 UTC by pointerish

We have implemented the followin:

- Background with image
- Navbar with gradient
- Footer

2020-09-28 18:06 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Hello team! Good job with its project so far! 👍 
The navbar is almost a copy of the original, well done! ⭐ 
You have clean code and a great readme file 👏 
Good job setting up the linters 🟢 

However, you need to make some changes before approving the project! 💪 
Kindly, apply the required changes and resubmit your project for a new code review ⏩ 

Check my comments below 👇 

Good luck, guys! 😃 

- There is a problem on your website, this is how it looks the live link. I have created a new one and the result is the same, also with different screen sizes
![Capture1](https://user-images.githubusercontent.com/56809963/94468846-5a4b4700-01c5-11eb-81fa-2f83aaba2db5.PNG)
![Capture](https://user-images.githubusercontent.com/56809963/94468855-5c150a80-01c5-11eb-8ac3-5a711ccbbd7b.PNG)

- Kindly fix the size of the main section and the background image
      -The CSS background should `cover` the whole page irrespective of the screen size.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/background_size_requirement.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538830/))

- Remove the horizontal scrollbar
- Add the text in the main section
- Add a hover effect to the navbar links

2020-09-28 18:06 UTC, javitocor commented on index.html
> +            <nav>
you can use a `header` tag here

2020-09-28 18:06 UTC, javitocor commented on index.html
> +        <div class="bottom-footer">
here also can use a `footer` tag

2020-09-28 18:06 UTC, javitocor commented on style.css
> +  position: relative;
it is a better practice to use classes instead of main selectors

2020-09-28 18:06 UTC, javitocor commented on style.css
> +  display: inline-flex;
same here

2020-09-28 18:06 UTC, javitocor commented on style.css
> +  text-align: center;
same here

2020-09-28 18:06 UTC, javitocor commented on style.css
> +  width: 80%;
same here

2020-09-28 18:06 UTC, javitocor commented on index.html
> +        <div class="nav-text-section">
you can use a `main` tag in here

2020-09-28 20:18 UTC, pointerish commented
Hi TSEs,

I submitted a new review request for the changes requested. I used the Chrome tool to emulate other resolutions since I'm on 1080p and the previous sizings looked okay for me.

2020-09-28 21:08 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

#### Hi, @pointerish and @che30,

Great job so far 👍, there are still changes that are necessary for this project to be approved.

Please see the [original page](https://web.archive.org/web/20140301004610/http://www.apple.com/) for proper reference

- [ ] The CSS background should cover the whole page irrespective of the screen size using the background-size and position properties.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/background_size_requirement.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538830/)). See [original archive page](https://web.archive.org/web/20140301004610/http://www.apple.com/). You can use `background-size: cover`  
![app](https://user-images.githubusercontent.com/5264771/94486012-b4083d00-01d6-11eb-82e6-9928ed0cf909.jpg)


I have made some comments below on your code, please work on them.

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-09-28 21:08 UTC, acushlakoncept commented on index.html
> +            </div>
Please this is strongly discouraged as the purpose of this project is to master how to position elements using CSS.
 ### Use text and not a screenshot of the text, header element preferably
<img width="656" alt="Screen Shot 2020-09-28 at 9 47 55 PM" src="https://user-images.githubusercontent.com/5264771/94484455-5c68d200-01d4-11eb-828a-1e2d5cbd21c3.png">
<img width="813" alt="Screen Shot 2020-09-28 at 9 48 03 PM" src="https://user-images.githubusercontent.com/5264771/94484461-5f63c280-01d4-11eb-8230-cc099c94b4ea.png">
<img width="584" alt="Screen Shot 2020-09-28 at 9 48 09 PM" src="https://user-images.githubusercontent.com/5264771/94484463-6094ef80-01d4-11eb-99d5-b7e31d140136.png">

2020-09-29 20:40 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave: Hello!! Great effort!!

:100: I like you used media queries even if it wasn't required.

## Required Changes
### [Mandatory] :red_circle: 

- [ ] ```<header>``` and ```<footer>``` should be outside the ```<main>``` container. These sections should follow this structure.
```
...
  <header>
    <nav>
      ... nav elements ...
    </nav>
  </header>
  
  <main>
    ... content ...
  </main>

  <footer>
    ... footer elements ...
  </footer>
```

- [ ] Navbar should be an unordered list,  with the ```<a>``` tag wrapped around ```<li>``` tag. See inline comments

- [ ] The bottom menu should also be an unordered list,  with the ```<a>``` tag wrapped around ```<li>``` tag. See inline comments

- [ ] There should be only one ```<footer>```. Merge both footers into one. I know this was a previous request. The issue comment wasn't clear enough but was meant to wrap that section in the footer, not to create a new footer section. I apologize for the misunderstanding.

### [OPTIONAL]  :large_blue_circle: 

- [x] Prefer custom CSS selectors over general ones. They are more specific and easier to identify. It helps readability. Example:
**Actual**:
```
.navbar > a:hover {
  ... some properties...
}
```
**Improved** :+1: :
```
.navbar__link:hover {
  ... some properties...
}
```

- [x] Keep your code Dry. Example:
**Actual**:
```
.right-footer-container > a {
  text-decoration: none;
  color: #08c;
}

.left-footer > p > a {
  text-decoration: none;
  color: #08c;
}
```
**Improved** :+1: :
```
.right-footer-container > a,
.left-footer > p > a {
  text-decoration: none;
  color: #08c;
}
```

### [Comments] :green_circle: 

- The website it is not displaying correctly on smaller screens and is making it look distorted. This observation is out of this project scope and requirements, still is worth mentioning. It a great habit to use the browser inspector mode, and the media query inspector to avoid these issues and see if the page looks as intended in different screen sizes. 

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-09-29 23:54 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-29 23:58 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @pointerish and @che30
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly work on the suggested changes 👇.

### Header
- [ ] Please Fix the issue as prious TSE explained

|[Source Page](https://web.archive.org/web/20140301004610/http://www.apple.com/)|[Clone Page](https://che30.github.io/Apple-Clone-Microverse/)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/94628385-4a248c00-02d9-11eb-8d2f-76ce0888d65c.png)|![clone](https://user-images.githubusercontent.com/29689273/94628396-501a6d00-02d9-11eb-8252-41528169a726.png)|



##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-30 00:25 UTC, pointerish commented
Hi @umairarshadbutt 

I made the changes as requested by the previous TSE. These are screenshots of our Live Demo link on 1080, 720 and 768 resolutions:
https://file.io/Ed5Jcyfl0xnK

Check the Live Demo using the device emulator on the dev tools and let me know how it looks since I guess we are having resolution discrepancies here.

2020-09-30 01:15 UTC, umairarshadbutt commented
Hi @pointerish  
Thanks for reaching me. I reviewed it again. This link (https://file.io/Ed5Jcyfl0xnK) is not working so I'm attaching the screen shots from the live link.

|720px|768px|1080px|
|:---:|:---:|:---:|
|![720](https://user-images.githubusercontent.com/29689273/94632356-b5735b80-02e3-11eb-8246-ab1d71e6a59d.png)|![768](https://user-images.githubusercontent.com/29689273/94632421-e0f64600-02e3-11eb-85a2-d8a8c8173f48.png)|![1080](https://user-images.githubusercontent.com/29689273/94632443-f79c9d00-02e3-11eb-9373-74149ccde37a.png)|

2020-09-30 01:21 UTC, pointerish commented
Hi @umairarshadbutt 

Apologies for the broken link. Here's the zip on Google Drive: https://drive.google.com/file/d/15Zik302Mqvujvf16Ss3fQL_W8tGBrWpU/view?usp=sharing

Also, the 720, 768 and 1080 are meant to be the second value for the resolution, not the first one.

The values are 1366x720, 1366x786 and 1920x1080.

2020-09-30 01:48 UTC, umairarshadbutt commented
Hi @umairarshadbutt
You can submit for re-review

2020-09-30 02:02 UTC, pointerish commented
As discussed with @umairarshadbutt this site has been tested on 14xx width resolutions and it's behaving as requested. I will proceed to request a new code review.

2020-09-30 02:09 UTC, jubaan approved these changes
# Status: Approved :tada: :tada: :tada:

## Congratulations team! I admire the effort you put on the project. 

You have corrected all previously required changes and now you may merge to master!

## See you at the top :rocket:!!

2020-09-30 02:10 UTC, merged